### PR TITLE
I have added a html resource card.

### PR DESCRIPTION
**Pull request by Babunshil**
https://user-images.githubusercontent.com/106283743/231224308-5d07adf5-09da-4f0b-a8a7-1f6e26a57020.mp4

### CODE REVIEW

**Review by ayush-Shandilya — APPROVED** [review]

**Comment by ayush-Shandilya** [comment]
Please Do one more PR, It was already merged and can't be changed. So do one more change.

**Comment by Babunshil** [comment]
@ayush-Shandilya  Sir what about my this PR. is it not going to be count ?

**Comment by Babunshil** [comment]
@ayush-Shandilya Its possible to add hackodex2023-accepted tag on the merged PR itself .

**Comment by ayush-Shandilya** [comment]
I have added it.

**Pull request merged**
